# prometheus.yml
global:
  scrape_interval: 15s # 프로메테우스가 해당 컴포넌트로부터 얼마나 자주 스크랩을하는지
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']

  - job_name: 'coupon-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']
#      - targets: ['coupon-service:8081']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
#            alertmanager:9093 # 추후 AlertManager 추가 시 주석 해제