# Grafana가 Prometheus를 데이터 소스로 인식하고 연결하는 설정

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9091
    isDefault: true
    editable: false